### ISSUE TITLE
Repository appears twice in HACS

### ISSUE THREAD

**Issue by higbyk** [custom-cards/slider-button-card#19]
Not sure if this is an issue with your repository or with HACS. Your repository appears twice on my home assistant and others:
![Screenshot_20220622-074015.png](https://user-images.githubusercontent.com/17530451/175021175-f9052cc7-2ab0-43e9-a42c-325669416694.png)

**Comment by rohankapoorcom** [comment]
Thanks. We've gotten this fork added to HACS, but are waiting for https://github.com/hacs/default/pull/1388 to be merged to remove the broken original repo.

**Comment by danielbrunt57** [comment]
Will that take care of this issue also?

![image](https://user-images.githubusercontent.com/49846893/177096089-95166aba-f73c-4f5f-9ab6-bfa04bf6f7e2.png)

**Comment by rohankapoorcom** [comment]
That indicates that the abandoned version has been removed from HACS. You should remove that one and then install this one by searching for "Slider Button Card" in HACS.
