### ISSUE TITLE
Compact Mode Inline - not working

### ISSUE THREAD

**Issue by PhAzE-Variance** [custom-cards/slider-button-card#32]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
1.10.9

**Last working release (if known):**
N/A

**Browser and Operating System:**
Chrome - Windows 11
Android - HA App (Latest)

**Description of problem:**
When enabling compact mode with "compact: true" the icon and name are not inline. Instead, the icon is showing below the name. Unless you add the following which forces the icon and text to be inline with each other again:
action_button:
  show: true

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by rohankapoorcom** [comment]
I'm not able to reproduce this with 1.12.0. Please upload a screenshot and provide your full config if you run into this issue again.

![image](https://github.com/custom-cards/slider-button-card/assets/2511957/0526a709-0116-4b69-8244-a7bb5755860d)
