### ISSUE TITLE
Input_number?! How to?

### ISSUE THREAD

**Issue by pickonedev** [custom-cards/slider-button-card#33]
Hi!

Sorry if it was already discussed, I didn't find any info.
Can someone please tell me how can I use this addon "Slider Button Card" with an input_number entity?

Thank you in advance!

**Comment by pickonedev** [comment]
@lizsugar , @rohankapoorcom 

Please, a little help? Thank you!

**Comment by Jimmypl007** [comment]
I believe its an intended addition, pull request #7 but it is not yet added to the release.. ( i may be wrong).
I am also waiting for the feature.
