### ISSUE TITLE
Request direction: right to left

### ISSUE THREAD

**Issue by stefanbode** [custom-cards/slider-button-card#48]
Great work and hopefully the right active fork that is also used by HACS. Not easy to find.

I have automated doors that act like shutters, with positioning and all this magic.

Some doors open from left to right and some from right to left. To have a UI experience that the door move where you move the finger the last direction can make it. 

I was thinking in a workaround of inverting the color and also inverting the % on the right door. But this does not look well either.

**Comment by rohankapoorcom** [comment]
You found the active fork @stefanbode! Thanks for the feature request. I've added support for right-to-left sliders in #53 if you'd like to give it a shot before I merge and push it out. Here's what it looks like in my testing environment (the same light is controlled in all directions).

![image](https://github.com/custom-cards/slider-button-card/assets/2511957/47f4894a-5d3f-41e2-95a4-f1df606be0f4)

**Comment by stefanbode** [comment]
Thx. Be back tomorrow to check it out.

**Comment by danielbrunt57** [comment]
Thanks!  Much appreciated!!

**Comment by stefanbode** [comment]
Works perfectly. The only thing I did not catch directly: There is a restart required after the update.

**Comment by rohankapoorcom** [comment]
Interesting, a restart shouldn't be needed. However you do need to force refresh the page to clear the cache after installing the latest version with HACS.
