### ISSUE TITLE
The attribute isn't aligned vertically when in compact mode.

### ISSUE THREAD

**Issue by rohankapoorcom** [custom-cards/slider-button-card#58]
Thanks for adding this feature! Just wanted to quickly point out that I noticed the attribute isn't aligned vertically when in compact mode.

Let me know if you can't reproduce.

_Originally posted by @ScottG489 in https://github.com/custom-cards/slider-button-card/issues/55#issuecomment-1678956687_

**Comment by ScottG489** [comment]
Thanks for all your work on this project :)
