### ISSUE TITLE
Step size < 1

### ISSUE THREAD

**Issue by BrukerJan** [custom-cards/slider-button-card#72]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Windows 10/11 Crome and Edge

**Description of problem:**
If an 'input_number' has 'step_size' < 1, the card apparently cannot use this to change the value of the helper, but uses 'step_size' 1 instead. If I change the value using an 'entities_card' , which works, then the 'slider-button-card' displays the value correctly with decimals.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by jlopez77** [comment]
I think this is the same issue described in #66, maybe it should be merged.

**Comment by rohankapoorcom** [comment]
Thanks, closed as a dupe.
